### ISSUE TITLE
江北LUG 线下聚会活动物资申请

### ISSUE THREAD

**Issue by ghost** [FZUG/tickets#2]
### 1. 开场并主题演讲
	King’s Way（南信大）: 人和宇宙的关系 - 虚拟化逃逸技术漫谈
	MuYu（南工大）: 南京热 不热 - vue入门
### 3. 主题演讲
	myppeter（南信大）: BGP讲解
	刘淑雯 ：机器学习入门
###### 预期人数: 10-30人

> 联系人 \<[ouyangjun1999@gmail.com](mailto:ouyangjun1999@gmail.com)\>

**Comment by sztsian** [comment]
As per discussion, we've agreed to sponsor some stickers and DVDs.
经过讨论，同意资助一些贴纸和Fedora光盘。

**Comment by alick** [comment]
@sztsian , close?
